region                  = "eu-central-1"
environment             = "staging"
aws_credentials_profile = "localstack"
spark_jobs_file_path    = "../../apps/glue_jobs/data_lake_etl.py"
lambda_file_path        = "../../apps/lambda_jobs_trigger/trigger_job.zip"
